# Generated by Django 2.2.2 on 2021-11-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectABC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objabcmodel',
            name='productGas',
        ),
        migrations.RemoveField(
            model_name='objabcmodel',
            name='productOil',
        ),
        migrations.AddField(
            model_name='objabcmodel',
            name='product',
            field=models.CharField(default='oil', max_length=125),
            preserve_default=False,
        ),
    ]
