# Generated by Django 2.2.2 on 2021-11-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectABC', '0002_auto_20211104_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objabcmodel',
            name='priceUC1',
        ),
        migrations.RemoveField(
            model_name='objabcmodel',
            name='priceUC2',
        ),
        migrations.AddField(
            model_name='objabcmodel',
            name='priceUC',
            field=models.CharField(default='on', max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='bc_mmscfg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='fixedCost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='gasPerc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='gasPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='gasProdCost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='gasSD',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='indProdCost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='oilPerc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='oilPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='oilProdCost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='oilSD',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='royalty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objabcmodel',
            name='scf_bo',
            field=models.FloatField(),
        ),
    ]
