# Generated by Django 2.2.2 on 2021-11-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectABC', '0003_auto_20211104_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objabcmodel',
            old_name='excelFile',
            new_name='hedgedExcelFile',
        ),
        migrations.AddField(
            model_name='objabcmodel',
            name='outputExcelFile',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
