# Generated by Django 2.2.2 on 2021-11-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjBModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oilPrice', models.IntegerField()),
                ('oilSD', models.IntegerField()),
                ('gasPrice', models.IntegerField()),
                ('gasSD', models.IntegerField()),
                ('percLine', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ObjAModel',
        ),
    ]
