# Generated by Django 2.2.2 on 2021-12-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectB', '0002_auto_20211102_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objbmodel',
            name='gasPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='objbmodel',
            name='oilPrice',
            field=models.FloatField(),
        ),
    ]
