# Generated by Django 2.2.2 on 2021-10-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjAModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodType', models.CharField(max_length=200)),
                ('threshold', models.PositiveIntegerField()),
                ('curveType', models.CharField(max_length=200)),
                ('excelFile', models.CharField(max_length=200)),
            ],
        ),
    ]
