# Generated by Django 2.2.2 on 2021-10-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objamodel',
            name='threshold',
            field=models.CharField(max_length=200),
        ),
    ]
